/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Pc
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    public void switchpanel(JPanel panel) {
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }

    public AdminForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        switchpanel(UpdateCategoryPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Update_category_header_Btn = new javax.swing.JButton();
        Add_Item_header_Btn = new javax.swing.JButton();
        Delete_User_header_Btn = new javax.swing.JButton();
        Show_orders_header_Btn = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        AddItemPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ItemName_txt2 = new javax.swing.JTextField();
        itemAmount_txt2 = new javax.swing.JTextField();
        add_item_btn2 = new javax.swing.JButton();
        item_categoryID_txt2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        itemPrice_txt3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        image2_txt2 = new javax.swing.JTextField();
        image1_txt2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        UpdateCategoryPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        categoryName_txt = new javax.swing.JTextField();
        categoryID_txt = new javax.swing.JTextField();
        add_category_btn = new javax.swing.JButton();
        update_category_btn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Delete_user_panel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        user_ID_txt = new javax.swing.JTextField();
        Delete_User_Btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        show_orders_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        Enter_Date_txt = new javax.swing.JFormattedTextField();
        jLabel27 = new javax.swing.JLabel();
        Show_order_Btn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        headerPanel.setBackground(new java.awt.Color(0, 153, 204));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/icon/icons8-shopping-cart-24.png"))); // NOI18N
        jLabel6.setText("Online Shopping System");

        Update_category_header_Btn.setBackground(new java.awt.Color(0, 153, 204));
        Update_category_header_Btn.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        Update_category_header_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Update_category_header_Btn.setText("Update Category");
        Update_category_header_Btn.setBorder(null);
        Update_category_header_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Update_category_header_BtnMouseClicked(evt);
            }
        });
        Update_category_header_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_category_header_BtnActionPerformed(evt);
            }
        });

        Add_Item_header_Btn.setBackground(new java.awt.Color(0, 153, 204));
        Add_Item_header_Btn.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        Add_Item_header_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Add_Item_header_Btn.setText("Add Item");
        Add_Item_header_Btn.setBorder(null);
        Add_Item_header_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add_Item_header_BtnMouseClicked(evt);
            }
        });
        Add_Item_header_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Item_header_BtnActionPerformed(evt);
            }
        });

        Delete_User_header_Btn.setBackground(new java.awt.Color(0, 153, 204));
        Delete_User_header_Btn.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        Delete_User_header_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Delete_User_header_Btn.setText("Delete User");
        Delete_User_header_Btn.setBorder(null);
        Delete_User_header_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_User_header_BtnMouseClicked(evt);
            }
        });
        Delete_User_header_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_User_header_BtnActionPerformed(evt);
            }
        });

        Show_orders_header_Btn.setBackground(new java.awt.Color(0, 153, 204));
        Show_orders_header_Btn.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        Show_orders_header_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Show_orders_header_Btn.setText("Show orders");
        Show_orders_header_Btn.setBorder(null);
        Show_orders_header_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_orders_header_BtnMouseClicked(evt);
            }
        });
        Show_orders_header_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_orders_header_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(headerPanelLayout.createSequentialGroup()
                        .addComponent(Update_category_header_Btn)
                        .addGap(34, 34, 34)
                        .addComponent(Add_Item_header_Btn))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Delete_User_header_Btn)
                .addGap(27, 27, 27)
                .addComponent(Show_orders_header_Btn)
                .addGap(31, 31, 31))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update_category_header_Btn)
                    .addComponent(Add_Item_header_Btn)
                    .addComponent(Delete_User_header_Btn)
                    .addComponent(Show_orders_header_Btn)))
        );

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        AddItemPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setText("Name:");

        jLabel20.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel20.setText("Amount:");

        ItemName_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemName_txt2ActionPerformed(evt);
            }
        });

        itemAmount_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAmount_txt2ActionPerformed(evt);
            }
        });

        add_item_btn2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        add_item_btn2.setText("Add");
        add_item_btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_item_btn2MouseClicked(evt);
            }
        });
        add_item_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_item_btn2ActionPerformed(evt);
            }
        });

        item_categoryID_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_categoryID_txt2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel22.setText("Category ID:");

        itemPrice_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPrice_txt3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel23.setText("Price:");

        jLabel24.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel24.setText("Image-1:");

        jLabel25.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel25.setText("Image-2:");

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel13.setText("Add new product");

        javax.swing.GroupLayout AddItemPanel2Layout = new javax.swing.GroupLayout(AddItemPanel2);
        AddItemPanel2.setLayout(AddItemPanel2Layout);
        AddItemPanel2Layout.setHorizontalGroup(
            AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddItemPanel2Layout.createSequentialGroup()
                .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddItemPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(AddItemPanel2Layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(add_item_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddItemPanel2Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddItemPanel2Layout.createSequentialGroup()
                                            .addComponent(image1_txt2)
                                            .addGap(55, 55, 55)
                                            .addComponent(jLabel25))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddItemPanel2Layout.createSequentialGroup()
                                            .addComponent(itemPrice_txt3)
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel22)))))
                            .addGroup(AddItemPanel2Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(ItemName_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel20)))
                        .addGap(18, 18, 18)
                        .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(item_categoryID_txt2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(itemAmount_txt2)
                            .addComponent(image2_txt2)))
                    .addGroup(AddItemPanel2Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AddItemPanel2Layout.setVerticalGroup(
            AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddItemPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemName_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemAmount_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemPrice_txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item_categoryID_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(AddItemPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(image1_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(image2_txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(42, 42, 42)
                .addComponent(add_item_btn2)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        UpdateCategoryPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel1.setText("Category Name:");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setText("Category ID:");

        categoryName_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryName_txtActionPerformed(evt);
            }
        });

        categoryID_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryID_txtActionPerformed(evt);
            }
        });

        add_category_btn.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        add_category_btn.setText("Add");
        add_category_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_category_btnMouseClicked(evt);
            }
        });

        update_category_btn.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        update_category_btn.setText("Update");
        update_category_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_category_btnMouseClicked(evt);
            }
        });
        update_category_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_category_btnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel14.setText("Manage Category");

        javax.swing.GroupLayout UpdateCategoryPanelLayout = new javax.swing.GroupLayout(UpdateCategoryPanel);
        UpdateCategoryPanel.setLayout(UpdateCategoryPanelLayout);
        UpdateCategoryPanelLayout.setHorizontalGroup(
            UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateCategoryPanelLayout.createSequentialGroup()
                .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateCategoryPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jLabel14))
                    .addGroup(UpdateCategoryPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(add_category_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UpdateCategoryPanelLayout.createSequentialGroup()
                                .addComponent(update_category_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(categoryName_txt)
                            .addComponent(categoryID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        UpdateCategoryPanelLayout.setVerticalGroup(
            UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateCategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryName_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(UpdateCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_category_btn)
                    .addComponent(deleteBtn)
                    .addComponent(update_category_btn))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        Delete_user_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel26.setText("User ID:");

        Delete_User_Btn.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Delete_User_Btn.setText("Delete");
        Delete_User_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delete_User_BtnMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel15.setText("Delete User");

        javax.swing.GroupLayout Delete_user_panelLayout = new javax.swing.GroupLayout(Delete_user_panel);
        Delete_user_panel.setLayout(Delete_user_panelLayout);
        Delete_user_panelLayout.setHorizontalGroup(
            Delete_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_user_panelLayout.createSequentialGroup()
                .addGroup(Delete_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Delete_user_panelLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel15))
                    .addGroup(Delete_user_panelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(user_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Delete_user_panelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(Delete_User_Btn)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        Delete_user_panelLayout.setVerticalGroup(
            Delete_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delete_user_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(Delete_user_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_ID_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(Delete_User_Btn)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        show_orders_panel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "amount", "price", "status"
            }
        ));
        jScrollPane1.setViewportView(ordersTable);

        Enter_Date_txt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("20yy-M-d"))));

        jLabel27.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel27.setText("Enter Date:");

        Show_order_Btn.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        Show_order_Btn.setText("Show");
        Show_order_Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_order_BtnMouseClicked(evt);
            }
        });
        Show_order_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_order_BtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel16.setText("Show orders in period time");

        javax.swing.GroupLayout show_orders_panelLayout = new javax.swing.GroupLayout(show_orders_panel);
        show_orders_panel.setLayout(show_orders_panelLayout);
        show_orders_panelLayout.setHorizontalGroup(
            show_orders_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show_orders_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(156, 156, 156))
            .addGroup(show_orders_panelLayout.createSequentialGroup()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enter_Date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Show_order_Btn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        show_orders_panelLayout.setVerticalGroup(
            show_orders_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, show_orders_panelLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(show_orders_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Enter_Date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Show_order_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLayeredPane1.setLayer(AddItemPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(UpdateCategoryPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(Delete_user_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(show_orders_panel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UpdateCategoryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddItemPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Delete_user_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(show_orders_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(UpdateCategoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(AddItemPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Delete_user_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(show_orders_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Update_category_header_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Update_category_header_BtnMouseClicked
        // TODO add your handling code here:
        //jLayeredPane1.removeAll();


    }//GEN-LAST:event_Update_category_header_BtnMouseClicked

    private void Update_category_header_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_category_header_BtnActionPerformed
        // TODO add your handling code here:
        switchpanel(UpdateCategoryPanel);
    }//GEN-LAST:event_Update_category_header_BtnActionPerformed

    private void Add_Item_header_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add_Item_header_BtnMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_Add_Item_header_BtnMouseClicked

    private void categoryName_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryName_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryName_txtActionPerformed

    private void categoryID_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryID_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryID_txtActionPerformed

    private void add_category_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_category_btnMouseClicked
        // TODO add your handling code here:
        Admin a = new Admin();
        String name = categoryName_txt.getText();
        int id = Integer.parseInt(categoryID_txt.getText());
        Category c = new Category(id, name);
        a.add_category(c);
        
        JOptionPane.showMessageDialog(this, "Category added");
        categoryID_txt.setText("");
        categoryName_txt.setText("");
    }//GEN-LAST:event_add_category_btnMouseClicked

    private void update_category_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_category_btnMouseClicked
        // TODO add your handling code here:
        Admin a = new Admin();
        String name = categoryName_txt.getText();
        int id = Integer.parseInt(categoryID_txt.getText());
        Category c = new Category(id, name);
        a.edit_category(c);
        
        
        JOptionPane.showMessageDialog(this, "Category updated");
        categoryID_txt.setText("");
        categoryName_txt.setText("");
    }//GEN-LAST:event_update_category_btnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        // TODO add your handling code here:
        Admin a = new Admin();
        String name = categoryName_txt.getText();
        int id = Integer.parseInt(categoryID_txt.getText());
        Category c = new Category(id, name);
        a.delete_category(id);
        
        JOptionPane.showMessageDialog(this, "Category deleted");
        categoryID_txt.setText("");
        categoryName_txt.setText("");
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void ItemName_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemName_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ItemName_txt2ActionPerformed

    private void itemAmount_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAmount_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAmount_txt2ActionPerformed

    private void add_item_btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_item_btn2MouseClicked
        // TODO add your handling code here:
        String name = ItemName_txt2.getText();
        String image1 = image1_txt2.getText();
        String image2 = image2_txt2.getText();
        int categoryID = Integer.parseInt(item_categoryID_txt2.getText());
        float price = Float.parseFloat(itemPrice_txt3.getText());
        int amount = Integer.parseInt(itemAmount_txt2.getText());
        Admin a = new Admin();
        Product p = new Product(0, price, categoryID, amount, name, image1, image2);
        a.add_product(p);
        
        JOptionPane.showMessageDialog(this, "Product added");
        
        ItemName_txt2.setText("");
        itemAmount_txt2.setText("");
        itemPrice_txt3.setText("");
        item_categoryID_txt2.setText("");
        image1_txt2.setText("");
        image2_txt2.setText("");
    }//GEN-LAST:event_add_item_btn2MouseClicked

    private void item_categoryID_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_categoryID_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_categoryID_txt2ActionPerformed

    private void itemPrice_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPrice_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemPrice_txt3ActionPerformed

    private void Delete_User_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_User_BtnMouseClicked
        // TODO add your handling code here:
        Admin a = new Admin();
        int user_id = Integer.parseInt(user_ID_txt.getText());
        a.delete_user(user_id);
        
        JOptionPane.showMessageDialog(this, "User deleted");
        user_ID_txt.setText("");
    }//GEN-LAST:event_Delete_User_BtnMouseClicked

    private void Delete_User_header_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delete_User_header_BtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Delete_User_header_BtnMouseClicked

    private void Delete_User_header_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_User_header_BtnActionPerformed
        // TODO add your handling code here:
        switchpanel(Delete_user_panel);
    }//GEN-LAST:event_Delete_User_header_BtnActionPerformed

    private void Show_orders_header_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_orders_header_BtnMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Show_orders_header_BtnMouseClicked

    private void Show_order_BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_order_BtnMouseClicked
        // TODO add your handling code here:
        String date = Enter_Date_txt.getText();

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
                getOrder(date),
                new String[]{
                    "Id", "Amount", "Price", "Status"
                }
        ));
    }//GEN-LAST:event_Show_order_BtnMouseClicked

    private void Add_Item_header_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Item_header_BtnActionPerformed
        // TODO add your handling code here:
        switchpanel(AddItemPanel2);
    }//GEN-LAST:event_Add_Item_header_BtnActionPerformed

    private void Show_orders_header_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_orders_header_BtnActionPerformed
        // TODO add your handling code here:
        switchpanel(show_orders_panel);
    }//GEN-LAST:event_Show_orders_header_BtnActionPerformed

    private void add_item_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_item_btn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_item_btn2ActionPerformed

    private void update_category_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_category_btnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_update_category_btnActionPerformed

    private void Show_order_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_order_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Show_order_BtnActionPerformed
    public int checkItem(String name) {

        try {
            // TODO add product to cart.
            DBHelper dBHelper = DBHelper.getInstance();

            dBHelper.setQuery("select amount from designpattern.product where (name)=(?)");
            PreparedStatement preparedStmt = dBHelper.getPreparedStmt();

            preparedStmt = dBHelper.getMyconnection().prepareStatement(dBHelper.getQuery());
            preparedStmt.setString(1, name);
            ResultSet rs = preparedStmt.executeQuery();

            if (rs.next()) {
                return rs.getInt(1);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        return 0;
    }

    public Object[][] getOrder(String date) {
        Object[][] obj = new Object[20][4];
        try {
            // TODO add product to cart.
            DBHelper dBHelper = DBHelper.getInstance();

            dBHelper.setQuery("select id,amount,product_price,status from designpattern.users_order where (buying_date)=(?)");
            PreparedStatement preparedStmt = dBHelper.getPreparedStmt();

            preparedStmt = dBHelper.getMyconnection().prepareStatement(dBHelper.getQuery());
            preparedStmt.setString(1, date);
            ResultSet rs = preparedStmt.executeQuery();
            int row = 0;
            while (rs.next()) {

                obj[row][0] = rs.getString(1);
                obj[row][1] = rs.getString(2);
                obj[row][2] = rs.getString(3);
                obj[row][3] = rs.getString(4);
                row++;

            }

        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        return obj;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddItemPanel2;
    private javax.swing.JButton Add_Item_header_Btn;
    private javax.swing.JButton Delete_User_Btn;
    private javax.swing.JButton Delete_User_header_Btn;
    private javax.swing.JPanel Delete_user_panel;
    private javax.swing.JFormattedTextField Enter_Date_txt;
    private javax.swing.JTextField ItemName_txt2;
    private javax.swing.JButton Show_order_Btn;
    private javax.swing.JButton Show_orders_header_Btn;
    private javax.swing.JPanel UpdateCategoryPanel;
    private javax.swing.JButton Update_category_header_Btn;
    private javax.swing.JButton add_category_btn;
    private javax.swing.JButton add_item_btn2;
    private javax.swing.JTextField categoryID_txt;
    private javax.swing.JTextField categoryName_txt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField image1_txt2;
    private javax.swing.JTextField image2_txt2;
    private javax.swing.JTextField itemAmount_txt2;
    private javax.swing.JTextField itemPrice_txt3;
    private javax.swing.JTextField item_categoryID_txt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ordersTable;
    private javax.swing.JPanel show_orders_panel;
    private javax.swing.JButton update_category_btn;
    private javax.swing.JTextField user_ID_txt;
    // End of variables declaration//GEN-END:variables
}
